CREATE DATABASE IF NOT EXISTS FishForecast;
USE FishForecast;

CREATE TABLE users ( 
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    discordId VARCHAR(20) NOT NULL, 
    isSubscribed BOOLEAN NOT NULL DEFAULT FALSE,
    isSetup BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE preferences ( 
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    userID INTEGER NOT NULL, 
    zipcode VARCHAR(5) NOT NULL, 
    location VARCHAR(255) NOT NULL,
    species VARCHAR(50) NOT NULL,
    sendTime TIME NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
);